-- GENERAR EL DDL

DROP DATABASE IF EXISTS proyecto_reservas ; -- reserv_ar

CREATE DATABASE proyecto_reservas;

USE proyecto_reservas;

-- Tabla RESERVA
CREATE TABLE RESERVA (
    IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDTALLER INT,
    IDPUESTO INT,
    IDEMPLEADO INT,
    IDTIPOTRABAJO INT,
    FECHA DATETIME,
    CANCELACION DATETIME DEFAULT NULL
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDTIPOTRABAJO INT,
    IDTALLER INT
);

-- Tabla DUEÑO
CREATE TABLE DUENO (
    IDDUENO INT PRIMARY KEY AUTO_INCREMENT,
    IDTALLER INT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20)
);

-- Tabla TIPOTRABAJO
CREATE TABLE TIPOTRABAJO (
    IDTIPOTRABAJO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50),
    DURACIONPROM INT NOT NULL
);

-- Tabla TALLER
CREATE TABLE TALLER (
    IDTALLER INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);

-- Tabla PUESTO_TRABAJO
CREATE TABLE PUESTO_TRABAJO (
    IDPUESTO INT PRIMARY KEY AUTO_INCREMENT,
    IDTALLER INT,
    CAPACIDAD INT,
    DISPONIBLE BOOLEAN
);



-- FOREIGN KEYS DEFINITION

-- EMPLEADO

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDTALLER) REFERENCES TALLER(IDTALLER);

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_TRABAJO
    FOREIGN KEY (IDTIPOTRABAJO) REFERENCES TIPOTRABAJO(IDTIPOTRABAJO);

-- DUEÑO

ALTER TABLE DUENO
    ADD CONSTRAINT FK_DUE_TAL
    FOREIGN KEY (IDTALLER) REFERENCES TALLER(IDTALLER);
    
-- PUESTO DE TRABAJO

ALTER TABLE PUESTO_TRABAJO
    ADD CONSTRAINT FK_PUESTO_TALLER
    FOREIGN KEY (IDTALLER) REFERENCES TALLER(IDTALLER);
    
-- RESERVAS

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_TALLER
    FOREIGN KEY (IDTALLER) REFERENCES TALLER(IDTALLER);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_PUESTO
    FOREIGN KEY (IDPUESTO) REFERENCES PUESTO_TRABAJO(IDPUESTO);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
    
ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_TIPOTRABAJO
    FOREIGN KEY (IDTIPOTRABAJO) REFERENCES TIPOTRABAJO(IDTIPOTRABAJO);
